### test
GET http://laravel.otus/api/test?api_token=SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl
Accept: application/json

### GET users
GET http://laravel.otus/api/users
Accept: application/json
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl

### GET user
GET http://laravel.otus/api/users/2
Accept: application/json
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl


### DELETE user
DELETE http://laravel.otus/api/users/4
Accept: application/json

### POST webhook
POST https://7908-212-12-20-139.ngrok-free.app/webhook
Content-Type: application/x-www-form-urlencoded

name = Max &
email = maxim.b3@intensa.ru &
password = R2NuUuLTHLeFFQYw

### POST user
POST http://laravel.otus/api/users
Content-Type: application/x-www-form-urlencoded

name = Max &
email = maxim.b3@intensa.ru &
password = R2NuUuLTHLeFFQYw


### PUT user
PUT http://laravel.otus/api/users/2
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl

name = WithToken


### GET reports v1
GET http://laravel.otus/api/v1/reports
Accept: application/json
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl

### CREATE reports v1
POST http://laravel.otus/api/v1/reports
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl

status = Created &
utility_id = 233 &
project_id = 1

### UPDATE reports v1
PUT http://laravel.otus/api/v1/reports/160
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl

status = Created &
utility_id = 232 &
project_id = 2

### show report v1
GET http://laravel.otus/api/v1/reports/138
Accept: application/json
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl

### DELETE reports v1
DELETE http://laravel.otus/api/v1/reports/137
Accept: application/json
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl

### GET reports v2
GET http://laravel.otus/api/v2/reports
Accept: application/json
Authorization: Bearer SeC6uOdA0dVy8hPQ1B4hFuhHxVhpJwwaJ6GcHZv5sRR3IcQce38PYNq7h4dl
